### ISSUE TITLE
Reduce the size of the container by removing pacman cache

### ISSUE THREAD

**Issue by corrieriluca** [FrancoisDtm/Epita-Container#1]
Hi!

I would like to make a suggestion to reduce the size of the Docker image which is huge (and that's *normal*).

Removing `pacman` cache could contribute to that reducing as stated on [ArchWiki](https://wiki.archlinux.org/index.php/Pacman#Cleaning_the_package_cache) 😄 

I recommend the most *agressive* approach as adviced on the wiki page, by adding this line after the last `pacman` operation in the Dockerfile:
```Dockerfile
RUN pacman -Scc --noconfirm
```

Tested and approved ! 👍 (but not on your image unfortunately, I'm in a train right now ! 😅)

**Comment by FrancoisDtm** [comment]
Hey Luca!

Thanks for your advice! I've added your contribution. You can see it here 2bf7ab6f34a5f59db2de46187cf1fd1569e2a08b 👍🏻

The first version of the image was huge, about ... 2.19 GB.
I've managed to reduce it to 1.63 GB in version 1.1.

_Thanks to you, it is now even less! 💜_

**Comment by corrieriluca** [comment]
You're welcome!

Congrats for the great Docker image you've been able to make! 😄
